version: '2'
services:
  postgres:
    container_name: clair_postgres
    image: postgres:9.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  clair:
    container_name: clair_clair
    image: clair:v2.0.6
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./config.yaml:/config/config.yaml
    command: [-config, /config/config.yaml]
